spring.datasource.url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&serverTimezone=Europe/Moscow&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none

bezkoder.app.jwtSecret: bezKoderSecretKey
bezkoder.app.jwtExpirationMs: 86400000

upload:
  path: "C:/Users/Valet/Desktop/storage"