spring.datasource.url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&serverTimezone=Europe/Moscow&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 128MB
  jackson:
    mapper:
      default-view-inclusion: true
jwt:
  token:
    secret: blogEngineDevolekSecretKey
    expired: 86400000

upload:
  path: "C:/Users/Valet/Desktop/storage"

captcha:
  width: 100
  height: 35
  font-size: 20
post:
  title:
    minLength: 10
  text:
    minLength: 500

project.name: <Блог для разработчиков/>

captcha.expirationMs: 3600000

spring.mail:
  # Логин и пароль пользователя от почты на gmail
  host: smtp.gmail.com
  port: 587
  username: blogengineskillbox@gmail.com
  password: "|HK@$Q20"
  # Other properties
  properties.mail.smtp:
    auth: true
    connectiontimeout: 5000
    timeout: 5000
    writetimeout: 5000
    # TLS , port 587
    starttls.enable: true