spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
    username: root
    password: testtest
  jpa.hibernate.ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 128MB
  jackson:
    mapper:
      default-view-inclusion: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
server:
  port: ${PORT:8080}
jwt:
  token:
    secret: blogEngineDevolekSecretKey
    expired: 86400000
    cookieName: "Authorization"

upload:
  path: @root.path@

captcha:
  width: 100
  height: 35
  font-size: 20
post:
  title:
    minLength: 10
  text:
    minLength: 500
  comment:
    minLength: 10
user:
  password:
    minLength: 6
  photo:
    width: 36
db:
  pathToRootJks: @root.path@/db/root.jks
  rootJksPassword: testtest

project:
  name: <Блог для разработчиков/>
  info:
    title: "DevPub"
    subtitle: "Рассказы разработчиков"
    phone: "+7 965 787-12-34"
    email: "mail@mail.ru"
    copyright: "Наумов Валентин"
    copyrightFrom: "2020"
  link:
    changePassword: "/login/change-password/"
    expiredMessage: "Ссылка для восстановления пароля устарела.\n \t<a href=\"/auth/restore\">Запросить ссылку снова</a>"


captcha.expirationMs: 3600000

spring.mail:
  # Логин и пароль пользователя от почты на gmail
  host: smtp.gmail.com
  port: 587
  username: blogengineskillbox@gmail.com
  password: "|HK@$Q20"
  # Other properties
  properties.mail.smtp:
    auth: true
    connectiontimeout: 5000
    timeout: 5000
    writetimeout: 5000
    # TLS , port 587
    starttls.enable: true